# Generated by Django 2.2.4 on 2020-03-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('mobile', models.IntegerField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('location_type', models.PositiveIntegerField(choices=[(0, 'Country'), (1, 'City'), (2, 'Zip')], default=1)),
                ('location_string', models.CharField(max_length=20)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
