# Generated by Django 2.2.4 on 2020-03-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200318_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsolution',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
